server:
  port: 8082
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:~/restaurante
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
